#!/usr/bin/env ruby
require 'r-fxxk'

class Matsumura < Brainfuck
nxt "わびに肉奢るわ"
inc "オッスオラ元ツイ廃！"
prv "かーたーさんばいばーい"
dec "ワロタｗｗｗｗｗｗｗｗｗｗｗｗｗｗｗ"
opn "焼肉するかぁ"
cls "アラサーが調子に乗ってごめんな…"
put "まだ若いもん！！！！"
get "こんなの絶対おかしいよ"
end

puts Matsumura.new.fuck(ARGF.read)
